title: 정현성
description: > # this means to ignore newlines until "baseurl:"
  저를 소개하는 블로그입니다.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://12345k67.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: 정현성
tagline: 학생
about-description: 야구를 좋아함 # Add Discription 
pic: hhhhh.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: hj5298610@naver.com # Add your Email address
phone: 010 2387 1317 # Add your Phone number
github: 12345k67 # Add your Github handle


# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
